In [1]:
import sys
sys.path.append("C:/Users/Pierre Houdouin/Desktop/Gaussian process/Code")
from samplers import SyntheticSampler
from preprocessings import preprocessing
from gaussian_process_model import GaussianProcessSKlearn, GaussianProcessGPMP, GaussianProcessGPyTorch

Using backend: torch


# Parameters

In [2]:
### Data generation
input_dimension     = 1
x_length            = 10
function_name       = "multimodal sinus"
function_parameters = {"power sinus"      : {"Power"        : 2},
                       "heaviside"        : {"x gaps"       : [0, 0.5, 1], 
                                             "y values"     : [0, -0.5], 
                                             "sigma noises" : [0.01, 0.01]},
                       "multimodal sinus" : {"x gaps"       : [0, 3, 6, 10], 
                                             "speed values" : [0.5, 0.5, 0.5]},
                       }

N_function          = 1000
N_observed          = 25

### Gaussian process model
kernel_name                     = "RBF"
kernel_parameters_optimization  = {"sigma0"                   : 1                              ,
                                   "Length scale"             : 1                              ,
                                   "Length scales"            : [1, 1, 1, 1]                   ,
                                   "Noise"                    : 1e-2                           ,
                                   "Lower bound sigma0"       : 0.1                            ,
                                   "Upper bound sigma0"       : 5                              ,
                                   "Lower bound length scale" : 0.1                            ,
                                   "Upper bound length scale" : 5                              ,
                                   "Lower bound noise"        : 1e-4                           ,
                                   "Upper bound noise"        : 1e1                            ,
                                   "SKlearn"       : {"N restarts optimizer" : 20},
                                   "GPMP"          : {}                           ,
                                   "GPyTorch"      : {"Training iterations" : 50}
                                  }
optimize_kernel_hyperparameters = True

# Data generation

In [3]:
synthetic_sampler = SyntheticSampler(input_dimension, x_length, function_name, function_parameters)
function_samples  = synthetic_sampler.sample(N_function)
observed_samples  = synthetic_sampler.extract_from_samples(N_observed, function_samples)

# GPMP Gaussian process model

### GPMP preprocessing

In [4]:
library                                        = "GPMP"
X_function, X_observed, Y_function, Y_observed = preprocessing(library, function_samples, observed_samples)

### GPMP gaussian process model training

In [5]:
gaussian_process_GPMP         = GaussianProcessGPMP(X_observed, Y_observed, kernel_name, kernel_parameters_optimization, optimize_kernel_hyperparameters)
gaussian_process_GPMP.train_gaussian_process_model()
posterior_mean, posterior_std = gaussian_process_GPMP.predict(X_function)
gaussian_process_parameters   = gaussian_process_GPMP.gaussian_process_parameters

In [6]:
posterior_mean, posterior_std

(array([ 0.15840299,  0.15854169,  0.15970132,  0.17423363,  0.19478423,
         0.21175081,  0.21367014,  0.23290837,  0.24996233,  0.33074901,
         0.35695295,  0.37739236,  0.3826484 ,  0.42907009,  0.43942241,
         0.47813584,  0.47861689,  0.52456658,  0.52786465,  0.55105927,
         0.56820861,  0.59126138,  0.62127197,  0.63132801,  0.63516507,
         0.64539145,  0.67529015,  0.69289474,  0.72273604,  0.7391065 ,
         0.75345089,  0.75934261,  0.76974216,  0.78560995,  0.7898617 ,
         0.80225053,  0.80877556,  0.83394825,  0.92110528,  0.92117928,
         0.93069448,  0.93186331,  0.95378452,  0.95634469,  0.97121527,
         0.9715999 ,  0.97232489,  0.9787983 ,  0.97902427,  0.98169859,
         0.98201391,  0.97833265,  0.97783851,  0.9633834 ,  0.96263681,
         0.95887128,  0.95875727,  0.95659711,  0.94422851,  0.92993207,
         0.9130911 ,  0.89401791,  0.89157541,  0.87666483,  0.87381653,
         0.86871584,  0.84987656,  0.8169575 ,  0.7

In [7]:
gaussian_process_parameters

{'sigma0': 0.8159212980119276,
 'Noise': 0.01,
 'Length scale 0': 0.6873833058402851}

# SKlearn Gaussian process model

### SKlearn preprocessing

In [8]:
library                                        = "SKlearn"
X_function, X_observed, Y_function, Y_observed = preprocessing(library, function_samples, observed_samples)

### SKlearn gaussian process model training

In [9]:
gaussian_process_sklearn      = GaussianProcessSKlearn(X_observed, Y_observed, kernel_name, kernel_parameters_optimization, optimize_kernel_hyperparameters)
gaussian_process_sklearn.train_gaussian_process_model()
posterior_mean, posterior_std = gaussian_process_sklearn.predict(X_function)
gaussian_process_parameters   = gaussian_process_sklearn.gaussian_process_parameters

C:\Users\Public\anaconda_file\envs\py38\lib\site-packages\sklearn\gaussian_process\kernels.py:420: ConvergenceWarning: The optimal value found for dimension 0 of parameter k2__noise_level is close to the specified lower bound 0.0001. Decreasing the bound and calling fit again may find a better value.
  warnings.warn(


In [10]:
posterior_mean, posterior_std

(array([ 0.03243247,  0.03263747,  0.03435067,  0.05570236,  0.08553462,
         0.10985763,  0.11259221,  0.13981727,  0.1636778 ,  0.27347655,
         0.30802886,  0.33464423,  0.34144213,  0.4006872 ,  0.41371009,
         0.46182359,  0.46241574,  0.5183508 ,  0.52231868,  0.55005051,
         0.57036158,  0.59741009,  0.63219185,  0.64373889,  0.6481307 ,
         0.65979748,  0.69359073,  0.71326824,  0.74624998,  0.76414249,
         0.77970239,  0.78606109,  0.7972386 ,  0.81417805,  0.81869295,
         0.83178966,  0.83865178,  0.86488595,  0.95226752,  0.9523388 ,
         0.96144723,  0.9625577 ,  0.98294635,  0.98525742,  0.99814955,
         0.99846429,  0.99905336,  1.00391543,  1.00406165,  1.00528047,
         1.00499828,  0.99887023,  0.99823054,  0.98131421,  0.9804833 ,
         0.9763252 ,  0.97620008,  0.97383674,  0.96052138,  0.94544499,
         0.92796299,  0.9084137 ,  0.90592537,  0.8907969 ,  0.88791801,
         0.88277057,  0.86383892,  0.83100792,  0.8

In [11]:
gaussian_process_parameters

{'sigma0': 1.21471254397328,
 'Noise': 0.00010000000000000009,
 'Length scale': 0.6661160283943297}

# GPyTorch

### GPyTorch preprocessing

In [12]:
library                                        = "GPyTorch"
X_function, X_observed, Y_function, Y_observed = preprocessing(library, function_samples, observed_samples)

### GPyTorch gaussian process model training

In [13]:
gaussian_process_gpytorch = GaussianProcessGPyTorch(X_observed, Y_observed, kernel_name, kernel_parameters_optimization, optimize_kernel_hyperparameters)
gaussian_process_gpytorch.train_gaussian_process_model()
posterior_mean, posterior_std = gaussian_process_gpytorch.predict(X_function)
gaussian_process_parameters   = gaussian_process_gpytorch.gaussian_process_parameters

In [14]:
posterior_mean, posterior_std

(array([ 0.08731179,  0.08748333,  0.0889173 ,  0.10684425,  0.13206134,
         0.15276607,  0.1551019 ,  0.17844501,  0.19903369,  0.2953126 ,
         0.32612254,  0.35001969,  0.35614615,  0.40993075,  0.4218471 ,
         0.46616447,  0.46671276,  0.51881873,  0.52253863,  0.548625  ,
         0.56782867,  0.59353163,  0.6268021 ,  0.63790247,  0.64213166,
         0.65338601,  0.68614688,  0.70533629,  0.73769173,  0.75534789,
         0.77076326,  0.77707961,  0.78820663,  0.80512922,  0.80965207,
         0.82280232,  0.82971102,  0.85624669,  0.94638218,  0.94645719,
         0.95607301,  0.95724972,  0.97908242,  0.98159411,  0.99589037,
         0.99624978,  0.99692492,  1.00273175,  1.00292134,  1.00487939,
         1.00487228,  0.99968947,  0.99909599,  0.98274043,  0.98191969,
         0.97779863,  0.97767429,  0.9753226 ,  0.96198001,  0.94673698,
         0.9289411 ,  0.90893264,  0.90637934,  0.89082945,  0.88786569,
         0.88256311,  0.86302745,  0.82904781,  0.8

In [15]:
gaussian_process_parameters

{'sigma0': 0.9061574605780288,
 'Noise': 0.002073766709727551,
 'Length scale 0': 0.5513515820570197}