In [1]:
import sys
sys.path.append("C:/Users/Pierre Houdouin/Desktop/Gaussian process/Code")
from samplers import SyntheticSampler
from preprocessings import preprocessing

# Parameters

In [2]:
### Data generation
input_dimension     = 3
x_length            = 10
function_name       = "multimodal sinus"
function_parameters = {"power sinus"      : {"Power"        : 2},
                       "heaviside"        : {"x gaps"       : [0, 0.5, 1], 
                                             "y values"     : [0, -0.5], 
                                             "sigma noises" : [0.01, 0.01]},
                       "multimodal sinus" : {"x gaps"       : [0, 3, 6, 10], 
                                             "speed values" : [10, 30, 60]},
                       }

N_function          = 100
N_observed          = 10

# Data generation

In [3]:
synthetic_sampler = SyntheticSampler(input_dimension, x_length, function_name, function_parameters)
function_samples  = synthetic_sampler.sample(N_function)
observed_samples  = synthetic_sampler.extract_from_samples(N_observed, function_samples)

# GPMP Preprocessing

In [4]:
library                                        = "GPMP"
X_function, X_observed, Y_function, Y_observed = preprocessing(library, function_samples, observed_samples)
X_observed, Y_observed

(array([[1.4161585 , 4.74039688, 3.81543422],
        [5.64822725, 3.89699612, 1.08232632],
        [8.55837368, 8.86186753, 5.65108596],
        [1.9030789 , 4.44160055, 1.17199507],
        [0.73573142, 3.39693133, 2.39316519],
        [3.95866761, 1.4128305 , 5.22954998],
        [6.37892936, 1.20732617, 6.23206097],
        [2.9352811 , 7.61694905, 6.23746531],
        [9.85759999, 7.57262022, 9.06357158],
        [3.42567908, 6.04717433, 6.76279585]]),
 array([-0.9821646 , -0.88671517,  0.98272013,  0.86627215,  0.99864721,
         0.19627878,  0.58264106, -0.60315708, -0.71816012,  0.42280717]))

# SKlearn Preprocessing

In [5]:
library                                        = "SKlearn"
X_function, X_observed, Y_function, Y_observed = preprocessing(library, function_samples, observed_samples)
X_observed, Y_observed

(array([[1.4161585 , 4.74039688, 3.81543422],
        [5.64822725, 3.89699612, 1.08232632],
        [8.55837368, 8.86186753, 5.65108596],
        [1.9030789 , 4.44160055, 1.17199507],
        [0.73573142, 3.39693133, 2.39316519],
        [3.95866761, 1.4128305 , 5.22954998],
        [6.37892936, 1.20732617, 6.23206097],
        [2.9352811 , 7.61694905, 6.23746531],
        [9.85759999, 7.57262022, 9.06357158],
        [3.42567908, 6.04717433, 6.76279585]]),
 array([-0.9821646 , -0.88671517,  0.98272013,  0.86627215,  0.99864721,
         0.19627878,  0.58264106, -0.60315708, -0.71816012,  0.42280717]))

# GPyTorch

In [6]:
library                                        = "GPyTorch"
X_function, X_observed, Y_function, Y_observed = preprocessing(library, function_samples, observed_samples)
X_observed, Y_observed

(tensor([[1.4162, 4.7404, 3.8154],
         [5.6482, 3.8970, 1.0823],
         [8.5584, 8.8619, 5.6511],
         [1.9031, 4.4416, 1.1720],
         [0.7357, 3.3969, 2.3932],
         [3.9587, 1.4128, 5.2295],
         [6.3789, 1.2073, 6.2321],
         [2.9353, 7.6169, 6.2375],
         [9.8576, 7.5726, 9.0636],
         [3.4257, 6.0472, 6.7628]], dtype=torch.float64),
 tensor([-0.9822, -0.8867,  0.9827,  0.8663,  0.9986,  0.1963,  0.5826, -0.6032,
         -0.7182,  0.4228], dtype=torch.float64))